import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier/flat";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Disables every ESLint rule that would conflict with Prettier.
  // Must stay last so it wins over the configs above.
  prettier,
  {
    rules: {
      // Stubs and interface implementations legitimately ignore arguments.
      // Prefixing with `_` is the documented way to say "on purpose".
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Cloudflare / OpenNext build output (see README).
    ".open-next/**",
    ".wrangler/**",
    // shadcn/ui primitives are generated by the CLI and re-synced on update.
    "src/components/ui/**",
  ]),
]);

export default eslintConfig;
